### ISSUE TITLE
Update to latest underscore 

### ISSUE THREAD

**Issue by pbcomm** [rweng/underscore-rails#27]
Update to latest 1.8.3 version of underscore

**Comment by rweng** [comment]
PR please

**Comment by zacharyabresch** [comment]
:+1:

**Comment by AdrienGiboire** [comment]
:+1:

**Comment by smcabrera** [comment]
It looks like this has been committed--can the issue be closed?

**Comment by travisjeffery** [comment]
yeah 1.8.3 is on rubygems already. thanks!
